name: app_hobbystore
description: "A new Flutter project."
publish_to: 'none'
version: 0.3.0+4

environment:
  sdk: ^3.12.1

dependencies:
  cached_network_image: ^4.0.4
  flutter:
    sdk: flutter
  http: ^1.6.0
  otp_auth:
    path: ../packages/otp_auth
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
